FROM centos:7
RUN yum -y install openssh-server

#RUN useradd remote_user && \
RUN useradd jenkins && \
    echo "1234" | passwd jenkins  --stdin && \
    mkdir /home/jenkins/.ssh && \
    chmod 700 /home/jenkins/.ssh

COPY $PWD/ssh/remote-ki.pub /home/jenkins/.ssh/authorized_keys

RUN chown jenkins:jenkins   -R /home/jenkins && \
    chmod 400 /home/jenkins/.ssh/authorized_keys

RUN ssh-keygen -A

#RUN yum -y install mysql

RUN yum -y install epel-release && \
    yum -y install python3-pip && \
    pip3 install --upgrade pip && \
    pip3 install awscli

CMD /usr/sbin/sshd -D
